# Permalinks
permalink:           pretty

# Setup
title:               Gaurav Kandlikar
tagline:
url:                 http://gauravsk.github.io
paginate:            2
baseurl:             ""
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Gaurav Kandlikar
  url:               https://twitter.com/gauravsk_
  email:             gaurav.kandlikar@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/gauravsk/gauravsk.github.io
markdown: kramdown
# Gems
plugins:
  - jekyll-paginate
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
pages_list:
  Projects: '/projects'
  Blog: '/blog'
  Recipes: '/recipes'
  Archive: '/archive'
  Reading: '/reading'
